name: recipes_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dart_mappable: ^4.5.0
  multiple_result: ^5.2.0
  http: ^1.4.0
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_mappable_builder: ^4.5.0
  hive_ce_generator: ^1.8.2
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
